### ISSUE TITLE
🎃🍂 Improve the UI of the website

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#1]
# Goal

Welcome Hacktoberfest! The goal of this issue is to improve the UI of the website of [this project](https://afulls.top).
## Description

Currently the UI is very plain and doesn't have a lot of content. The goal is to create a nicer looking UI possibly with headers and footers and more content!

Be Creative!

For example, you could make the website change background every 10 seconds. Scroll down to see other suggestions.

The new design must not be intrusive with user experience. Eg. No bright red backgrounds.
## Ideas (?)

Dont let the below ideas limit your creativity. Multiple designs can be created and a different one can be loaded every time a user enters.
- Dictionary styled definition of full stop. (@conscou)
- Changing background colors (@conscou)
- Kindergarten drawing styled webpage
- Changeable themes and interactive content?
- Implement animation (perhaps [animate.css](https://daneden.github.io/animate.css/)) (@anu0012)
- typed.js implementation ([typed.js](http://www.mattboldt.com/demos/typed-js/))
- (!!!!) A very cool [parallax.js](http://matthew.wagerfield.com/parallax/) implementation

It would be amazing for you to comment down below if you are interested in this project!
## Contribute?

Please read `CONTRIBUTION.MD`

**Comment by kzisme** [comment]
@choyiny  Any ideas in-particular?

**Comment by constantina-js** [comment]
So I'm new to working open source things. I forked the repo and did something super basic, which is to change the background color each time a person visits the page.

I was thinking that we can a dictionary-styled definition of a full stop somewhere on the page as well?

**Comment by choyiny** [comment]
@kzisme I dont have any solid ideas right now, but I like the idea of @conscou making a dictionary-styled definition of full stop on the page. EDIT: added some descriptions in main thread

@conscou Do you know how to open a pull request? Just venture to [this page](https://github.com/choyiny/afullstop/pulls) and click new pull request to get started. Click "Compare across forks" and change your fork as the head fork, and mine as the base.

**Comment by constantina-js** [comment]
@choyiny yeah I had accidentally closed it and reopened it lol. But I think it should have went through? Again, it was a really basic change and I limited the color choices for now.

**Comment by choyiny** [comment]
@conscou I have merged it! With regards to your idea of a dictionary styled page, [this font](https://fonts.google.com/?category=Serif&selection.family=Playfair+Display) seems good for it. 

`<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
`

**Comment by constantina-js** [comment]
@choyiny Font is perfect! As far as how to show the definition, I'm torn between either having the first full stop in "This is a full stop..." a different color and then the user can hover over it and the definition would appear, or we just have a separate element on the page in which the user clicks it and the definition becomes visible below it.

Thoughts?

**Comment by choyiny** [comment]
#2

**Comment by choyiny** [comment]
@conscou The page doesn't have much stuff at the moment. I think we should first scrap the CSS framework I've been using and put the text to the center of the webpage. As there is not much content, I think having it all on the webpage is good enough. However, I am fine with both. Maybe I can learn some more javascript along the way.

**Comment by anu0012** [comment]
what type of content we can add ?

**Comment by choyiny** [comment]
@anu0012 I have added a bunch of ideas at the very top! We can also discuss some of your ideas here if you have any. I hope this repo can help you expand your knowledge on HTML, CSS and Javascript so feel free to play around.

**Comment by anu0012** [comment]
@choyiny we can add some animation to the text .

**Comment by choyiny** [comment]
@anu0012 definitely, make a pull request and see what you can come up with! It will also be great if you guys can spin up github pages for your fork so we can view the result easily.

**Comment by alejandro-sg** [comment]
Thanks for putting this into Hacktoberfest. I have already forked the repo and ready to get ideas flowing!

**Comment by choyiny** [comment]
@jasierragarcia Welcome! Feel free to give ideas so I can add it to the main thread!

**Comment by calvinrbnspiess** [comment]
Hello @choyiny ! I am really interested in creating a design. I already forked the repository, and I want to create an old computer terminal looking design with typewriting effect if you agree with this idea. Full stop.

**Comment by choyiny** [comment]
@Vailfire good idea! Read `CONTRIBUTION.MD` and start a PR!

**Comment by alejandro-sg** [comment]
@choyiny Since one of ideas you guys offered is to change the background color, I think I can work on making the color transition smooth with javascript and I can also work on adding a header and footer!

**Comment by kzisme** [comment]
I'll take a look at the latest commit/PR tonight or tomorrow and see what I
can add :)

**Comment by choyiny** [comment]
@jasierragarcia That sounds great, thanks!
@kzisme Thanks a lot!

**Comment by aakashkhatter1296** [comment]
@choyiny Should I create a new html file for the style change I wish to add ?

**Comment by choyiny** [comment]
@aakashkhatter1296 That's correct!

**Comment by choyiny** [comment]
Moving on to developing in the /js branch.
