### ISSUE TITLE
🎃🍂 Randomized pages

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#14]
## Description

Welcome Hacktoberfest 2016! Each HTML page includes a different design of “This is a full stop, not a period”. The goal is for the visitor to get a random page in `/pages/` every time they click “Really?” on https://afulls.top.
## Contribute?

Please read `CONTRIBUTING.MD` before creating your first pull request.
## Hacktoberfest 2016

This is part of a series of issues designed for Hacktoberfest 2016.

**Comment by hamer-iboshi** [comment]
I will work on it! Looks like cool.

**Comment by choyiny** [comment]
@hi15 That's great, thanks!

**Comment by cedricium** [comment]
I would love to be able to contribute! I've made an example page already, it can be found here: [cedricamaya.me/afullstop](http://cedricamaya.me/afullstop/). 

I'm fairly new to git/GitHub and not sure how exactly I should create a pull-request in order to contribute my page, if I could get some assistance that would be awesome!

**Comment by choyiny** [comment]
@cedricium Welcome to afullstop! First of all, please read the `CONTRIBUTING.MD` before making your first pull request.

You can make your pull request by clicking Pull Requests > New pull request > compare across forks; set your repository as the head fork, and mine as the base fork. Please make sure you do not edit `404.html`, but make your own file under `/pages/`. You can read more about the requirements of your pull request in `CONTRIBUTING.MD`!

**Comment by cedricium** [comment]
Thank you so much, I'll try it out right now. Just a quick question, is it okay if my page is titled "index.html" or will that mess something up?

**Comment by choyiny** [comment]
#19 addressed this.
