### ISSUE TITLE
🎃🍂 Improve Site Ranking (SEO)

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#21]
## Description

Welcome Hacktoberfest 2016! This task does not require previous programming experience. This project aims to remind people that this (.) is a full stop, not a period. Right now traffic to this site is minimal. The goal of this issue is to boost the site ranking of this project. There are several ways in tackling this issue:
- [x] Adding site favicon #23 
- [x] Add site metadata #26 
- [ ] Better linking with different pages
- [ ] Make the site worth visiting (?)
  And more...

If you have suggestions, add them below.
## Contribute?

Please read `CONTRIBUTING.MD` before making your first pull request.

**Comment by supermansi** [comment]
Hi! This is a great concept and I would love to improve the SEO. Should I edit the 404.html file directly (to add metadata)?

**Comment by choyiny** [comment]
@supermansi Yep.
