### ISSUE TITLE
🎃🍂 Migrate HTML designs from gh-pages to js

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#29]
## Description

This project is a website viewable at https://afulls.top/notaperiod/?name=Github. Currently, we have pages which has different designs stored at `/pages/` in `gh-pages` branch. We would like to migrate them to the new `js` branch created by @Vailfire. 
## Contribute?

Please read `CONTRIBUTION.MD` in `js` branch before creating your first pull request. There is extensive documentation on how to create a new page based on the old designs.
## Hacktoberfest 2016

This is part of a series of issues designed for Hacktoberfest 2016.

**Comment by choyiny** [comment]
@Vailfire Would you be kind enough to help review PRs from this issue? Thanks!

**Comment by calvinrbnspiess** [comment]
@choyiny Yes, of course! But I had not much time to work on this project in the last days as I have to do a lot of work for school. Still, I'm going to review PRs if I see them in time.
