### ISSUE TITLE
🎃🍂 Make this website configurable to be able to suit many other definitions!

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#7]
## Description

Welcome Hacktoberfest 2016! The goal of this issue is to make the webpage content configurable. Currently, the webpage reminds users that this (.) is not a **period**, but a **full stop**. By doing magic with listening to URLs, how about making the words configurable? For example, if user inputs:

`https://afulls.top/?incorrect=Chips?correct=Crisps?name=Stranger`

It will show them This is a bag of crisps, not a bag of chips!

You can format the URL however you like, the above is only an example. The goal is just to make it easily modifiable and configurable.
### Examples
- This is not a tire, it’s a tyre.
- These are not pajamas, they are pyjamas.
- This is not a cookie, it’s a biscuit.
## Contribute?

Please read `CONTRIBUTION.MD` before creating your first pull request.
## Hacktoberfest 2016

This is part of a series of issues designed for Hacktoberfest 2016. New to this? Try #1

**Comment by calvinrbnspiess** [comment]
It would be possible to change to a react implementation (nodejs based: webpack workflow, create-react-app, ...), which would allow defining the different designs as components. Then you could just pass the url parameters as properties down to the different design components. This would complicate the workflow at first but could have value in terms of maintenance and flexibility. The whole project might then be minifed to one single .html file.

**Comment by choyiny** [comment]
@Vailfire I would like it to be able to be hosted on Github Pages so I don't need an extra host though. Any other ideas?

**Comment by calvinrbnspiess** [comment]
@choyiny Yeah, sorry I didn't explained it exactly enough. The node.js workflow (required on your dev-machine) generates a minified file from all the sources. The minifed file would contain all the neccessary html and js, so it does not require any additional backend. The page could still be deployed to gh-pages.
But perhaps we don't need any additional workflow if we just add the relevant scripts by hand and renounce any special development environment and the included benefits. That would made it easier, but does no longer automatically generate a combined file of all designs.

**Comment by choyiny** [comment]
@Vailfire I am still trying to think of a good way of combining all the designs made by contributors. Perhaps visitors can be given a random page every time they access the website. What do you think?

With regards to automatic generation, it seems like a good idea. However, I am definitely not experienced with it. I have opened a new branch `js` so we can play around with it.

**Comment by calvinrbnspiess** [comment]
@choyiny Yeah, I like that idea and it seems definitely possible. I have some work for now with reinstalling my computer but I'll play around with it and I will open a pull request later this day.

**Comment by choyiny** [comment]
@Vailfire has implemented a `/js` branch.
