### ISSUE TITLE
🎃🍂 Background showing white sometimes

### ISSUE THREAD

**Issue by choyiny** [choyiny/afullstop#8]
### Issue

The background is sometimes white, which completely overlaps the white text.
### Possible fixes
- Make the text change color when background is white
- Disable the white color for background changes
### Contribution

Head on to `CONTRIBUTION.MD` before submitting your first pull request. Interested in something bigger? Check out #1 and #7

**Comment by blanyal** [comment]
PR #11 is a fix for this issue.

**Comment by choyiny** [comment]
Thanks, @blanyal

**Comment by blanyal** [comment]
You're welcome @choyiny
